backend:
  name: github
  repo: sahilosphere/cuvolti  
  branch: main
  base_url: https://decap-proxy-production-f192.up.railway.app   

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "article.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Tag", name: "tag", widget: "select", options: ["Opinion", "Tech", "Commerce", "Life"] }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Permalink", name: "permalink", widget: "string", hint: "Jaise: /articles/mera-naya-article/" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "src/about.njk"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Title", name: "title", widget: "hidden", default: "About" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/about/" }
          - { label: "Content (HTML)", name: "body", widget: "markdown" }
